name: Run java checkstyle
  uses: nikitasavinov/checkstyle-action@0.6.0
  with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  reporter: 'github-check'
  tool_name: 'testtool'
  level: 'error'
  fail_on_error: true
